# DELETE  http://127.0.0.1:8000/api/admin/siswa/3
# Content-Type: application/json
# Authorization: Bearer 9|Sh9vBfhuABWvW0xjZvmJnUvEiwA9eaQmVUjItwdVfa38a12f
# Accept: application/json

GET  http://127.0.0.1:8000/api/admin/siswa/qrcode
Content-Type: application/json
Authorization: Bearer 11|FyRwqedewnyMx6QI9Xd4zTmxp1TLR2yD9nJ1J7igfccd9b20
Accept: application/json

# POST http://127.0.0.1:8000/api/login
# Content-Type: application/json
# # Authorization: Bearer 9|Sh9vBfhuABWvW0xjZvmJnUvEiwA9eaQmVUjItwdVfa38a12f
# Accept: application/json

# {
#   "email": "hahahah@gmail.com",
#   "password": "password"
# }
